### ISSUE TITLE
Use kbase backend for works on android kernel 

### ISSUE THREAD

**Issue by Mateus2022** [Panfrost/panloader#1]
But android kernel (my bifrost) uses KBASE definitions/structs but panloader uses "MALI"? What a f0ck

**Comment by tokokudo** [comment]
> But android kernel (my bifrost) uses KBASE definitions/structs but panloader uses "MALI"? What a f0ck

The name doesn't affect the macro; the macro returns data from kbase (I know the repository isn't active).
